
version: '3.3'

# Usage:
#   docker stack deploy -c stack.yml mongo
# or 
#   docker-compose -f stack.yml up

services:

  mongo-docker:
    image: mongo
    #image: mongo:latest
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    # command: --smallfiles 
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongoadmin@mongo-docker:27017/ 

volumes:
  mongodb_data_volume:
    driver: local    
    


