version: '3' 
services:
  mongo-gui-docker:
    image: openkbs/mongo-gui-docker
    build:
      context: ./Dockerfile
    container_name: mongo-gui-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
#    ports:
#      - 8080:8080
    volumes:
      - ./workspace:/home/developer/workspace

