version: '3' 
services:
  mongo-gui-docker:
    image: openkbs/mongo-gui-docker
    command: /usr/bin/mongodb-compass
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: mongo-gui-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker-compose.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace

  

